#!/bin/bash 

# Check if empty 
if [ -z $1 ];then
       echo "No argument, use -h for help." 
       exit 0
fi

# Options
if [ $1 = "-h" ];then
        cat [path]/man/help_page
        exit 0
elif [ $1 = "-l" ];then
        ls [path]/man/
        exit 0
fi
